export const DEFAULT_QUESTIONS = 
[
  { id: 1, content: '说出“我”字', category: '日常' },
  { id: 2, content: '说出“你”字', category: '日常' },
  { id: 3, content: '说出“他”或“它”', category: '日常' },
  { id: 4, content: '说出“不知道”', category: '日常' },
  { id: 5, content: '说出“真的吗”或“确实”', category: '日常' },
  { id: 6, content: '说出任何英文单词', category: '日常' },
  { id: 7, content: '直呼对方的名字', category: '日常' },
  { id: 8, content: '发出明显的笑声', category: '日常' },
  { id: 9, content: '说话带有疑问语气 (问句)', category: '日常' },
  { id: 10, content: '说出“等一下”或“稍等”', category: '日常' },
  { id: 11, content: '扶眼镜或摸眼眶', category: '日常' },
  { id: 12, content: '查看手机屏幕', category: '日常' },
  { id: 13, content: '拿起杯子或喝水', category: '日常' },
  { id: 14, content: '做出点头的动作', category: '日常' },
  { id: 15, content: '手碰到自己的头发', category: '日常' },
  { id: 16, content: '身体向后靠在椅背上', category: '日常' },
  { id: 17, content: '叹气或深呼吸', category: '日常' },
  { id: 18, content: '摆弄手中的物体 (笔、鼠标等)', category: '日常' },
  { id: 19, content: '查看当前时间', category: '日常' },
  { id: 20, content: '跷二郎腿', category: '日常' },
  { id: 21, content: '抖腿', category: '日常' },
  { id: 22, content: '说出“卧槽”或类似感叹词', category: '日常' },
  { id: 23, content: '说出“牛逼”或类似赞美', category: '日常' },
  { id: 24, content: '说出“寄了”或“麻了”', category: '日常' },
  { id: 25, content: '说出“随便”或“都可以”', category: '日常' },
  { id: 26, content: '说出“吃啥”或提到食物', category: '日常' },
  { id: 27, content: '打哈欠', category: '日常' },
  { id: 28, content: '伸懒腰', category: '日常' },
  { id: 29, content: '双手交叉抱胸', category: '日常' },
  { id: 30, content: '摸下巴或刮胡子动作', category: '日常' },
  { id: 31, content: '挠痒痒', category: '日常' },
  { id: 32, content: '清嗓子或咳嗽', category: '日常' },
  { id: 33, content: '搓手', category: '日常' },
  { id: 34, content: '咬嘴唇或舔嘴唇', category: '日常' },
  { id: 35, content: '看天花板', category: '日常' },
  { id: 36, content: '说出“啊？”', category: '日常' },
  { id: 37, content: '说出“懂了”或“明白了”', category: '日常' },
  { id: 38, content: '说出“离谱”', category: '日常' },
  { id: 39, content: '说出“绝了”', category: '日常' },
  { id: 40, content: '说出“行”或“好”', category: '日常' },
  { id: 41, content: '说出“没毛病”', category: '日常' },
  { id: 42, content: '说出“绷不住了”', category: '日常' },
  { id: 43, content: '说出“细说”', category: '日常' },
  { id: 44, content: '说出“乐”或“难崩”', category: '日常' },
  { id: 45, content: '说出“急了”', category: '日常' },
  { id: 46, content: '说出“典”或“孝”', category: '日常' },
  { id: 47, content: '打开微信或QQ', category: '日常' },
  { id: 48, content: '打开B站', category: '日常' },
  { id: 49, content: '说出“兄弟”或“哥们”', category: '日常' },
  { id: 50, content: '抱怨天气（太热/太冷）', category: '日常' },
  { id: 51, content: '提到外卖或快递', category: '日常' },
  { id: 52, content: '说出“困了”或想睡觉', category: '日常' },
  { id: 53, content: '说出“饿了”', category: '日常' },
  { id: 54, content: '提到洗澡或上厕所', category: '日常' },
  { id: 55, content: '照镜子或看屏幕反光中的自己', category: '日常' },
  { id: 56, content: '说出任何数字（中文或英文）', category: '日常' },
  { id: 57, content: '说出任何颜色名称', category: '日常' },
  { id: 58, content: '连续说两遍同一个词 (如：对对、行行)', category: '日常' },
  { id: 59, content: '突然提高音量', category: '日常' },
  { id: 60, content: '突然压低声音', category: '日常' },
  { id: 61, content: '眨眼频率突然变快', category: '日常' },
  { id: 62, content: '用手托腮', category: '日常' },
  { id: 63, content: '手指敲击桌面', category: '日常' },
  { id: 64, content: '转笔或试图转笔', category: '日常' },
  { id: 65, content: '脱鞋或穿鞋', category: '日常' },
  { id: 66, content: '整理衣服或拉拉链', category: '日常' },
  { id: 67, content: '深情对视超过3秒', category: '日常' },
  { id: 68, content: '翻白眼', category: '日常' },
  { id: 69, content: '摇头', category: '日常' },
  { id: 70, content: '耸肩', category: '日常' },
  { id: 71, content: '说出“如果”或“假设”', category: '日常' },
  { id: 72, content: '说出“但是”或“不过”', category: '日常' },
  { id: 73, content: '说出“为什么”', category: '日常' },
  { id: 74, content: '说出“怎么说”', category: '日常' },
  { id: 75, content: '说出“有一说一”', category: '日常' },
  { id: 76, content: '说出“讲道理”', category: '日常' },
  { id: 77, content: '说出“确实是这样”', category: '日常' },
  { id: 78, content: '说出“我也觉得”', category: '日常' },
  { id: 79, content: '打响指', category: '日常' },
  { id: 80, content: '吹口哨', category: '日常' },
  { id: 81, content: '哼歌', category: '日常' },
  { id: 82, content: '自言自语', category: '日常' },
  { id: 83, content: '接电话或打电话', category: '日常' },
  { id: 84, content: '戴上或摘下耳机', category: '日常' },
  { id: 85, content: '给手机充电', category: '日常' },
  { id: 86, content: '寻找找不到的东西 (如钥匙、手机)', category: '日常' },
  { id: 87, content: '说出“哎呀”', category: '日常' },
  { id: 88, content: '说出“靠”', category: '日常' },
  { id: 89, content: '说出“烦死了”', category: '日常' },
  { id: 90, content: '说出“太卷了”或“卷王”', category: '日常' },
  { id: 91, content: '提到某位老师或导员', category: '日常' },
  { id: 92, content: '提到上课、早八或签到', category: '日常' },
  { id: 93, content: '提到考试、期末或挂科', category: '日常' },
  { id: 94, content: '提到学分或绩点(GPA)', category: '日常' },
  { id: 95, content: '说出“没钱了”或提到穷', category: '日常' },
  { id: 96, content: '提到网购或拼多多/淘宝', category: '日常' },
  { id: 97, content: '说出“无聊”', category: '日常' },
  { id: 98, content: '说出“牛哇”', category: '日常' },
  { id: 99, content: '说出“什么鬼”', category: '日常' },
  { id: 100, content: '说出“神经病”', category: '日常' },
  { id: 101, content: '说出“无敌了”', category: '日常' },
  { id: 102, content: '说出“起飞”', category: '日常' },
  { id: 103, content: '说出“破防了”', category: '日常' },
  { id: 104, content: '说出“红温了”', category: '日常' },
  { id: 105, content: '说出“逆天”', category: '日常' },
  { id: 106, content: '打开某个软件的设置界面', category: '日常' },
  { id: 107, content: '清理手机或电脑后台', category: '日常' },
  { id: 108, content: '调整屏幕亮度', category: '日常' },
  { id: 109, content: '调整设备音量', category: '日常' },
  { id: 110, content: '锁屏或点亮屏幕', category: '日常' },
  { id: 111, content: '站起来走动', category: '日常' },
  { id: 112, content: '坐下', category: '日常' },
  { id: 113, content: '从椅子上滑下去 (葛优瘫)', category: '日常' },
  { id: 114, content: '用力敲击键盘的回车键', category: '日常' },
  { id: 115, content: '鼠标疯狂连点', category: '日常' },
  { id: 116, content: '揉肚子', category: '日常' },
  { id: 117, content: '捏指关节发出响声', category: '日常' },
  { id: 118, content: '深呼吸准备说话', category: '日常' },
  { id: 119, content: '用手捂住嘴', category: '日常' },
  { id: 120, content: '指向对方', category: '日常' },
  { id: 121, content: '比划手势 (如OK、V字)', category: '日常' },
  { id: 122, content: '双手一摊表示无奈', category: '日常' },
  { id: 123, content: '看窗外', category: '日常' },
  { id: 124, content: '闭上眼睛超过2秒', category: '日常' },
  { id: 125, content: '揉脖子或转动颈部', category: '日常' },
  { id: 126, content: '说出“明天再说”', category: '日常' },
  { id: 127, content: '说出“下次一定”', category: '日常' },
  { id: 128, content: '说出“算了吧”', category: '日常' },
  { id: 129, content: '说出“随便你”', category: '日常' },
  { id: 130, content: '说出“太麻烦了”', category: '日常' },
  { id: 131, content: '说出“这谁顶得住”', category: '日常' },
  { id: 132, content: '说出“还行”或“也就那样”', category: '日常' },
  { id: 133, content: '说出“好兄弟”', category: '日常' },
  { id: 134, content: '说出“大佬”或“巨佬”', category: '日常' },
  { id: 135, content: '说出“菜鸡”或“太菜了”', category: '日常' },
  { id: 136, content: '提到放假或周末', category: '日常' },
  { id: 137, content: '提到女朋友或谈恋爱相关话题', category: '日常' },
  { id: 138, content: '提到熬夜', category: '日常' },
  { id: 139, content: '拿纸巾', category: '日常' },
  { id: 140, content: '扔垃圾', category: '日常' },
  { id: 141, content: '开关灯', category: '日常' },
  { id: 142, content: '拉窗帘', category: '日常' },
  { id: 143, content: '在椅子上转圈', category: '日常' },
  { id: 144, content: '脚尖点地', category: '日常' },
  { id: 145, content: '双手抱头', category: '日常' },
  { id: 146, content: '假装听不懂', category: '日常' },
  { id: 147, content: '重复对方刚刚说的话', category: '日常' },
  { id: 148, content: '说出“嗯”、“啊”、“哦”等单音节敷衍', category: '日常' },
  { id: 149, content: '说出“哈哈” (口头念出)', category: '日常' },
  { id: 150, content: '说出任何脏话或口头禅', category: '日常' },
  { id: 151, content: '提到有关“编程”或“代码”的话题', category: '专业' },
  { id: 152, content: '使用组合键 (如 Ctrl+C, Ctrl+V, Alt+Tab)', category: '专业' },
  { id: 153, content: '提到“报错”、“Bug”或“Exception”', category: '专业' },
  { id: 154, content: '打开终端/控制台界面', category: '专业' },
  { id: 155, content: '按下 F12 打开开发者工具', category: '专业' },
  { id: 156, content: '在浏览器刷新页面 (F5 或 Ctrl+R)', category: '专业' },
  { id: 157, content: '提到“前端”或“后端”', category: '专业' },
  { id: 158, content: '提到 React、Vite 或 Tailwind', category: '专业' },
  { id: 159, content: '提到 C 语言或指针', category: '专业' },
  { id: 160, content: '抱怨 Java 代码太长或啰嗦', category: '专业' },
  { id: 161, content: '提到 Linux、WSL 或 Ubuntu', category: '专业' },
  { id: 162, content: '狂按 Esc 键 (Vim 后遗症)', category: '专业' },
  { id: 163, content: '打出 :wq 或提到退出 Vim', category: '专业' },
  { id: 164, content: '提到 Git (如 push, pull, commit, 冲突)', category: '专业' },
  { id: 165, content: '打开或提到 GitHub / Gitee', category: '专业' },
  { id: 166, content: '复制粘贴代码', category: '专业' },
  { id: 167, content: '抱怨环境配置太难', category: '专业' },
  { id: 168, content: '提到 npm, pnpm 或 yarn', category: '专业' },
  { id: 169, content: '提到“部署”、“上线”或 Vercel', category: '专业' },
  { id: 170, content: '提到清除缓存或 LocalStorage', category: '专业' },
  { id: 171, content: '检查网络连接或 Ping 地址', category: '专业' },
  { id: 172, content: '提到“接口”、“API”或“JSON”', category: '专业' },
  { id: 173, content: '说出“跑起来了”或“没报错”', category: '专业' },
  { id: 174, content: '说出“昨天明明还是好的”', category: '专业' },
  { id: 175, content: '说出“这代码不是我写的”', category: '专业' },
  { id: 176, content: '说出“重启一下试试”', category: '专业' },
  { id: 177, content: '打开或提到 Stack Overflow / CSDN', category: '专业' },
  { id: 178, content: '提到“框架”、“库”或“组件”', category: '专业' },
  { id: 179, content: '提到物理、高数或线性代数', category: '专业' },
  { id: 180, content: '提到概率论、数字电路', category: '专业' },
  { id: 181, content: '提到“需求”、“产品经理”或“甲方”', category: '专业' },
  { id: 182, content: '提到“重构”或“屎山代码”', category: '专业' },
  { id: 183, content: '盯着屏幕发呆试图在大脑里跑代码', category: '专业' },
  { id: 184, content: '吐槽某个语言是“世界上最好的语言”', category: '专业' },
  { id: 185, content: '提到“面向对象”或“面向过程”', category: '专业' },
  { id: 186, content: '使用命令行输入 ls 或 cd', category: '专业' },
  { id: 187, content: '提到 zsh 或终端美化', category: '专业' },
  { id: 188, content: '抱怨内存泄漏或空指针异常', category: '专业' },
  { id: 189, content: '提到“死循环”', category: '专业' },
  { id: 190, content: '提到“异步”或“回调地狱”', category: '专业' },
  { id: 191, content: '提到“开源”或“白嫖”项目', category: '专业' },
  { id: 192, content: '讨论电脑配置或显卡', category: '专业' },
  { id: 193, content: '提到云服务器或租GPU', category: '专业' },
  { id: 194, content: '打开 VS Code 或 IDEA', category: '专业' },
  { id: 195, content: '切换输入法中英文状态', category: '专业' },
  { id: 196, content: '敲击代码时发出极大且急促的键盘声', category: '专业' },
  { id: 197, content: '说出“快做完了” (通常是谎言)', category: '专业' },
  { id: 198, content: '提到算法题或 LeetCode', category: '专业' },
  { id: 199, content: '提到设计模式或系统架构', category: '专业' },
  { id: 200, content: '对着屏幕骂出脏话 (面向屏幕编程)', category: '专业' },
  { id: 201, content: '提到具体的游戏名称 (明日方舟、终末地等)', category: '兴趣' },
  { id: 202, content: '提到“理智”或抱怨没有理智了', category: '兴趣' },
  { id: 203, content: '提到“抽卡”、“出货”或“沉船”', category: '兴趣' },
  { id: 204, content: '提到“合成玉”、“源石”或“氪金”', category: '兴趣' },
  { id: 205, content: '提到“干员”、“专精”或“精二”', category: '兴趣' },
  { id: 206, content: '提到“挂机”、“代理指挥”或“自律”', category: '兴趣' },
  { id: 207, content: '提到“抄作业”或攻略UP主 (萧然等)', category: '兴趣' },
  { id: 208, content: '说出“小杯”、“大杯”或“超大杯”', category: '兴趣' },
  { id: 209, content: '提到《明日方舟：终末地》', category: '兴趣' },
  { id: 210, content: '提到“集成工业”、“种田”或“建流水线”', category: '兴趣' },
  { id: 211, content: '提到“佩丽卡”或“协议核心”', category: '兴趣' },
  { id: 212, content: '提到“基建”或“排班”', category: '兴趣' },
  { id: 213, content: '提到“海猫”或“鹰角网络”', category: '兴趣' },
  { id: 214, content: '打开或提到 Gemini', category: '兴趣' },
  { id: 215, content: '说“问一下 AI”或“让 AI 帮我写”', category: '兴趣' },
  { id: 216, content: '提到“大模型”、“LLM”或“Prompt”', category: '兴趣' },
  { id: 217, content: '抱怨 AI 乱编、胡说八道或“幻觉”', category: '兴趣' },
  { id: 218, content: '让 AI 帮忙解释代码或找 Bug', category: '兴趣' },
  { id: 219, content: '提到“生成”、“渲染”或“训练”', category: '兴趣' },
  { id: 220, content: '提到 AIGC 或 AI 绘画工具', category: '兴趣' },
  { id: 221, content: '提到 Minecraft 或“我的世界”', category: '兴趣' },
  { id: 222, content: '提到“挖矿”、“钻石”或“红石”', category: '兴趣' },
  { id: 223, content: '提到“苦力怕”或“生存模式”', category: '兴趣' },
  { id: 224, content: '提到“平面设计”、“排版”或“海报”', category: '兴趣' },
  { id: 225, content: '吐槽某个UI/UX设计很丑', category: '兴趣' },
  { id: 226, content: '提到“字体”、“对齐”或“字号”', category: '兴趣' },
  { id: 227, content: '提到“图层”、“透明度”或 Photoshop', category: '兴趣' },
  { id: 228, content: '讨论某种特定的视觉风格 (如水墨风、废土风)', category: '兴趣' },
  { id: 229, content: '提到“二次元”或相关番剧', category: '兴趣' },
  { id: 230, content: '提到“肉鸽”或“集成战略”', category: '兴趣' },
  { id: 231, content: '提到“日常任务”或“清日常”', category: '兴趣' },
  { id: 232, content: '提到“限定池”或“井”', category: '兴趣' },
  { id: 233, content: '抱怨手机玩游戏发热或掉帧', category: '兴趣' },
  { id: 234, content: '看游戏资讯或贴吧/NGA', category: '兴趣' },
  { id: 235, content: '提到“剧情”或“过场动画”', category: '兴趣' },
  { id: 236, content: '说出“开服玩家”或讨论游戏资历', category: '兴趣' },
  { id: 237, content: '给AI发大段的文本要求提炼总结', category: '兴趣' },
  { id: 238, content: '测试AI能不能听懂某个特定的梗', category: '兴趣' },
  { id: 239, content: '评价Gemini的某个回答“太长了”或“没说到点子上”', category: '兴趣' },
  { id: 240, content: '复制AI生成的代码直接跑', category: '兴趣' },
  { id: 241, content: '提到心理学概念 (如阿德勒、课题分离)', category: '兴趣' },
  { id: 242, content: '提到“哲学”或开始深度探讨人生', category: '兴趣' },
  { id: 243, content: '提到视觉小说或游戏叙事', category: '兴趣' },
  { id: 244, content: '讨论某个角色的立绘或画风', category: '兴趣' },
  { id: 245, content: '打开 Figma 或类似的设计软件', category: '兴趣' },
  { id: 246, content: '提到“像素风”或“体素”', category: '兴趣' },
  { id: 247, content: '讨论某个游戏的 UI 界面做得好不好', category: '兴趣' },
  { id: 248, content: '对着游戏截图或录屏进行研究', category: '兴趣' },
  { id: 249, content: '提到“塔防”', category: '兴趣' },
  { id: 250, content: '提到“三维建模”或 3D 视角', category: '兴趣' },
  { id: 251, content: '在群里发游戏抽卡截图海豹跳脸', category: '兴趣' },
  { id: 252, content: '因为代码跑不通转而去打一把游戏', category: '兴趣' }
]
;
